=== Ben5501/glossary-storage/src/SprykerFeature/Zed/Transfer/Business/Model/Generator/TransferObjectDefinitionSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns="http://xsd.spryker.com"
        targetNamespace="http://xsd.spryker.com">
    <xs:element name="transfers">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="transfer" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="transfer">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="property" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="name"                type="xs:string"  use="required" />
            <xs:attribute name="implementsInterface" type="xs:string"  use="required" />
            <xs:attribute name="createCollection"    type="xs:boolean" use="optional" />
        </xs:complexType>
    </xs:element>
    <xs:element name="property">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required" />
            <xs:attribute name="type" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Ben5501/glossary-storage/src/SprykerFeature/Zed/Transfer/Communication/Console/data/transfer.xml
<?xml version="1.0"?>
<transfers xmlns="http://xsd.spryker.com"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://xsd.spryker.com ../../src/Spryker/TransferObjectDefinitionSchema.xsd">

    <transfer name="Alfa" implementsInterface="Cart\CartChangeTransferInterface">
        <property name="AlfaItem" type="AlfaItem" />
        <property name="changedCartItems" type="CartItem[]" />
        <property name="couponCode" type="string" default="AAA" />
        <property name="order" type="Sales\Order"/>
        <property name="userId" type="int"/>
        <property name="cartHash" type="string"/>
        <property name="isMerged" type="bool"/>
    </transfer>
    <transfer name="AlfaItem" createCollection="true" implementsInterface="Cart\CartItemTransferInterface">
        <property name="sku" type="string"/>
        <property name="uniqueIdentifier" type="string"/>
        <property name="options" type="array"/>
        <property name="quantity" type="int"/>
    </transfer>
    <transfer name="Alfa" implementsInterface="Demo\DemoTransferInterface">
        <property name="customer" type="Demo\Customer" />
    </transfer>
    <transfer name="Alfa" implementsInterface="Demo\DemoTransferInterface">
        <property name="hgghtg" type="Demo\Customer" />
    </transfer>
</transfers>
